### ISSUE TITLE
Issue with disconnection?

### ISSUE THREAD

**Issue by rzfzr** [thedroidgeek/oculus-wireless-adb#3]
Recently I have been trying to use the wireless adb but it seems like the adb status goes to offline after a minute or so, last time I used was a few updates ago (Quest 2), when I wake the device again the debugging switch on the app is off... I tried setting the battery optimization to off, but nothing happened, any ideas?

**Comment by thedroidgeek** [comment]
Battery optimization won't help you here as the service is managed by the OS, this app merely tells the system to enable the wireless ADB functionality, any further behavior is out of control for the app.
